#!/usr/bin/env bash
# Installs Nginx and configures it to serve "Hello World!" at the root with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!".

apt-get update
apt-get install -y nginx

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /etc/nginx/html/index.html

service nginx restart
