#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried at the root with a curl GET request.
# Configures it to redirect /redirect_me to another page with a "301 Moved Permanently" status.
# Configures it to serve a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo sed -i '/server_name _;/a\\tlocation /redirect_me {\n\t\treturn 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a\\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart

