#!/usr/bin/env bash
# Pings an IP address passed as an argument 5 times.
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
