#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/# listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

service nginx restart
