#!/usr/bin/env bash
# Configures Nginx server to listen on port 80.

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/# listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

service nginx start
kill "$(pgrep 'nginx' | head -1)"
