#!/usr/bin/env bash
# Displays different messages for loop iterations from 1 to 10 using a while loop.
#   - Displays "bad luck" for the 4th iteration
#   - Displays "good luck" for the 8th iteration
#   - Displays "Best School" for other iterations

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
