#!/usr/bin/env bash
# Displays the content of the current directory in a list format, showing only the part of the name after the first dash

for file in *; do
  if [[ -f "$file" ]]; then
    if [[ "$file" == *-* ]]; then
      echo "$file" | cut -d '-' -f2-
    else
      echo "$file"
    fi
  fi
done
