#!/usr/bin/env bash
# Configures an Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8


cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
