#!/usr/bin/env bash
# Use netcat (nc) to listen on port 98 on localhost.

# -l : Listen mode
# -p : Port number
# -n : Numeric-only IP addresses (no DNS)
# -v : Verbose mode
# -s : Source address (localhost)
nc -lvnp 98
