#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
