#!/usr/bin/env bash
id -u nginx &>/dev/null || useradd --no-create-home --shell /bin/false nginx
pkill apache2
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
